name: Shell Commands
on: [push]

permissions:
  issues: write
  actions: write
  checks: write
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello everyone"
      - name: multiline script
        run: |
         node -v
         npm -v

    
 